<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
		'ZendBehaviorModule\Module'                        => __DIR__ . '/Module.php',
		'ZendBehaviorModule\Controller\BehaviorController' => __DIR__ . '/src/ZendBehaviorModule/Controller/BehaviorController.php',
		'ZendBehaviorModule\Model\beh_log' 				   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorModel.php',
		'ZendBehaviorModule\Model\beh_logTable'			   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorTable.php',
		'ZendBehaviorModule\Model\beh_trigger' 			   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorModel.php',
		'ZendBehaviorModule\Model\beh_triggerTable'		   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorTable.php',
		'ZendBehaviorModule\Model\beh_response' 		   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorModel.php',
		'ZendBehaviorModule\Model\beh_responseTable'	   => __DIR__ . '/src/ZendBehaviorModule/Model/BehaviorTable.php',
		'ZendBehaviorModuleTest\Framework\TestCase'        => __DIR__ . '/tests/ZendBehaviorModule/Framework/TestCase.php',
		'ZendBehaviorModuleTest\SampleTest'                => __DIR__ . '/tests/ZendBehaviorModule/SampleTest.php',
);