<div class="hero-unit">
	<h1>
		<?php echo $this->translate('Welcome to Behavior Tracker');?>
	</h1>
</div>

<div class="row">
	<div class="span4">
		<p>
			<a class="btn btn-success" href="<?php echo $this->url('logentry') ?>"><?php echo $this->translate('Log Entry') ?>
				&raquo;</a>
		</p>
	</div>
		<div class="span4">
		<p>
			<a class="btn btn-success" href="<?php echo $this->url('displaylogs') ?>"><?php echo $this->translate('Display Logs') ?>
				&raquo;</a>
		</p>
	</div>
</div>
