<?php // module/Album/view/album/album/index.phtml: $title = 'Logs';
use ZendBehaviorModule\Model\beh_log;

use ZendBehaviorModule\Model\BehaviorTable;

$this->headTitle($title); ?>


<h1>
	<?php echo $this->escapeHtml($title); ?>
</h1>

<table class="table">
	<tr>
		<th>Timestamp</th>
		<th>Entry</th>
		<th>Trigger Title</th>

		<th>&nbsp;</th>
	</tr>
	<?php 
	$mytriggers = array();
	$mytriggers[0] = NULL;
	foreach ($beh_triggers as $beh_trigger) :
	$mytriggers[$beh_trigger->id] = $beh_trigger->title;
	endforeach;

	foreach ($beh_logs as $beh_log) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($beh_log->timestamp);?></td>
		<td><?php echo $this->escapeHtml($beh_log->entry);?></td>
		<td><?php echo $this->escapeHtml($mytriggers[$beh_log->trig_id]);?></td>
	</tr>
	<?php endforeach; ?>
</table>